"""Expiring signed download URLs for report artifacts (data-flow.md §3,
mcp-servers.md "Signed download URLs ... generated by FastAPI").

Report bytes live in GCS at the report server's deterministic layout
`runs/<run>/reports/<artifact_id>.<ext>`; orchestration turns a persisted
report `ArtifactReference` into a `ReportDownload` with a V4-signed,
time-limited HTTPS URL. URLs are never stored as session state — they
expire and are regenerated on every read (report endpoint, replays,
SessionDetail).

Local substitution (D15-5, settled empirically at increment 4): against
the compose fake-gcs-server the URL is signed with a committed throwaway
RSA key (`local_signing_key.pem` — not a secret; fake-gcs performs no
signature validation) and its host is rewritten to the configured
`ORCH_GCS_PUBLIC_URL` (the fake-gcs HTTPS port; TLS is self-signed, so
clients download with certificate verification relaxed locally). Without
`ORCH_GCS_PUBLIC_URL` the URL is signed with the ambient default
credentials (Cloud Run service account — Phase 8 wiring) and keeps the
real GCS host.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from pathlib import Path

from google.auth.credentials import AnonymousCredentials
from google.cloud import storage
from google.oauth2 import service_account
from review_schemas.api import ReportDownload
from review_schemas.synthesis import ArtifactReference

#: Throwaway local-only signer identity (fake-gcs never validates it).
_LOCAL_SIGNER_EMAIL = "local-signed-urls@fake-gcs.invalid"
_KEY_PATH = Path(__file__).with_name("local_signing_key.pem")

#: Mirror of the report server's object layout (report_mcp/storage.py).
def report_object_name(reference: ArtifactReference) -> str:
    """GCS object name for one rendered report artifact."""
    format_name = reference.type.removeprefix("report-")
    return f"runs/{reference.story_run_id}/reports/{reference.artifact_id}.{format_name}"


class ReportSigner:
    """Builds `ReportDownload` entries from persisted report references."""

    def __init__(
        self,
        *,
        bucket: str,
        ttl_seconds: int,
        public_url: str | None = None,
    ):
        """`public_url` enables the local fake-gcs substitution; without
        it, ambient default credentials sign against real GCS."""
        self._bucket_name = bucket
        self._ttl = timedelta(seconds=ttl_seconds)
        self._public_url = public_url.rstrip("/") if public_url else None
        self._client: storage.Client | None = None
        self._credentials = None

    @classmethod
    def from_settings(cls, settings) -> "ReportSigner":
        return cls(
            bucket=settings.bucket,
            ttl_seconds=settings.signed_url_ttl_seconds,
            public_url=settings.gcs_public_url,
        )

    def warm_up(self) -> None:
        """Build the signing client eagerly so misconfiguration (missing
        key file, unusable ambient credentials) fails at startup, not on
        the first report request."""
        self._bucket()

    def _bucket(self) -> storage.Bucket:
        if self._client is None:
            if self._public_url:
                credentials: service_account.Credentials | None = (
                    service_account.Credentials.from_service_account_info(
                        {
                            "client_email": _LOCAL_SIGNER_EMAIL,
                            "token_uri": "https://oauth2.g.googleapis.com/token",
                            "private_key": _KEY_PATH.read_text(),
                        }
                    )
                )
                client = storage.Client(
                    project="local", credentials=AnonymousCredentials()
                )
            else:
                credentials = None
                client = storage.Client(project="local")
            self._client = client
            self._credentials = credentials
        return self._client.bucket(self._bucket_name)

    def download(self, reference: ArtifactReference) -> ReportDownload:
        """One signed download entry for a report reference."""
        bucket = self._bucket()
        blob = bucket.blob(report_object_name(reference))
        expires_at = datetime.now(UTC) + self._ttl
        url = blob.generate_signed_url(
            version="v4",
            expiration=expires_at,
            credentials=self._credentials,
        )
        if self._public_url:
            url = _rewrite_host(url, self._public_url)
        return ReportDownload(
            reference=reference,
            format=reference.type.removeprefix("report-"),  # type: ignore[arg-type]
            signed_url=url,
            expires_at=expires_at,
        )

    def downloads(self, references: list[ArtifactReference]) -> list[ReportDownload]:
        """Signed entries for every persisted report reference."""
        return [self.download(reference) for reference in references]


def _rewrite_host(url: str, public_url: str) -> str:
    """Point a generated URL at the local fake-gcs endpoint instead of
    storage.googleapis.com (the fake-gcs README's client-side rewrite)."""
    marker = url.find("/", url.find("://") + 3)
    return f"{public_url}{url[marker:]}"
